apiVersion: v1
kind: Service
metadata:
  name: alloydb-store
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: alloydb-store-1 # by convention, use the name of the Service
                     # as a prefix for the name of the EndpointSlice
  labels:
    # You should set the "kubernetes.io/service-name" label.
    # Set its value to match the name of the Service
    kubernetes.io/service-name: alloydb-store
addressType: IPv4
ports:
  - name: '' # empty because port 9376 is not assigned as a well-known
             # port (by IANA)
    protocol: TCP
    port: 5432
endpoints:
  - addresses:
      - "10.128.0.63"
---
apiVersion: v1
kind: Service
metadata:
  name: alloydb-ingress
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: alloydb
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  loadBalancerSourceRanges:
  - 10.0.0.0/4
---
apiVersion: v1
kind: Service
metadata:
  name: alloydb-incloud
  labels:
    app: alloydb
spec:
  ports:
  - port: 5432
    name: postgres
  selector:
    app: alloydb